Revert "Performance improvement to QubitManager for Borrowing (#190)"
microsoft/qsharp-runtime pull request #391
Opened 2020-10-07 06:43 UTC by anpaz

This caused a huge drop performance on Toffoli, so reverting.

2020-10-07 06:50 UTC, anpaz commented
/AzurePipelines run

2020-10-10 18:16 UTC, DmitryVasilevsky commented on src/Simulation/Common/QubitManagerTrackingScope.cs
> -        public virtual IQArray<Qubit> Borrow(long numToBorrow)
Keeping this virtual is important for exploration experiments and layout benchmarks.

2020-10-12 05:13 UTC, msoeken requested changes
Looks good to me, but it would be good to modify the comment that changing loop direction can increase efficiency, and also add some more comments that we tried this change and why it did not work.

2020-11-14 00:03 UTC, irinayat-MS commented
@anpaz : Andres, I've effectively reverted #190 with #435. Could probably close this PR now?

2020-11-18 16:36 UTC, bettinaheim commented
Closing this PR since it is addressed with #435.

2020-11-18 16:36 UTC, closed without merging